export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ArticleLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Nested layouts should NOT contain <html> or <body> tags
  // Only the root layout (app/layout.tsx) should have those
  return (
    <>
      {children}
    </>
  )
}
